channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.0
  - pip:
      - azureml-mlflow==1.38.0
      - azure-ai-ml==1.0.0
      - azureml-inference-server-http==0.8.0
      - azureml-defaults==1.54.0
      - inference-schema[numpy-support]
      - pyarrow==10.0.0
      - scikit-learn==0.24.1
      - pandas==1.3.5
      - joblib==1.0.1
      - matplotlib==3.5.1
      - numpy==1.21.6
      - azure-storage-blob==12.11.0
      - azure-identity==1.10.0
      - mlflow==1.30.1
