# Copyright (c) Microsoft Corporation.  All rights reserved.
# Licensed under the MIT License.

name: deploy-model-training-pipeline

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      - template: ../../config-infra-prod.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      - template: ../../config-infra-dev.yml
  - name: version
    value: aml-cli-v2

trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: mlops-templates
      name: mlops-v2/mlops-templates
      type: git
      ref: main

stages:
  - stage: DeployTrainingPipeline
    displayName: Deploy Training Pipeline
    jobs:
      - job: DeployTrainingPipeline
        timeoutInMinutes: 360
        steps:
          - checkout: self
            path: s/
          - task: Bash@3
            displayName: "Prevent repos dir warnings"
            inputs:
              targetType: "inline"
              script: |
                set -e
                mkdir -p "$(Build.Repository.Name)"
                mkdir -p "mlops-templates"
          - checkout: mlops-templates
            path: s/templates/
          - template: templates/${{ variables.version }}/install-az-cli.yml@mlops-templates
          - template: templates/${{ variables. version }}/install-aml-cli.yml@mlops-templates
          - template: templates/${{ variables.version }}/connect-to-workspace.yml@mlops-templates
          - template: templates/${{ variables.version }}/register-environment.yml@mlops-templates
            parameters:
              environment_name: taxi-train-env
              environment_file: mlops/azureml/train/train-env.yml
          - template: templates/${{ variables.version }}/create-compute.yml@mlops-templates
            parameters:
              cluster_name: cpu-cluster
              size: Standard_DS3_v2
              min_instances: 0
              max_instances: 2
              cluster_tier: low_priority
          - template: templates/${{ variables.version }}/run-pipeline.yml@mlops-templates
            parameters:
              pipeline_file: mlops/azureml/train/pipeline.yml
              experiment_name: taxi-fare-training-$(Build. SourceBranchName)
              display_name: taxi-fare-run-$(Build.BuildID)
